-- Generated Database Schema — oracle
-- vygenerováno nástrojem DB v TORM Canvas, 2026-09-29
-- 2 tabulek, 9 příkazů

CREATE TABLE OBEC (
    KOD NUMBER(19),
    NAZEV VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_OBEC PRIMARY KEY (KOD)
);

COMMENT ON TABLE OBEC IS 'tabulkaobcí';

COMMENT ON COLUMN OBEC.KOD IS 'Primární klíč.';

CREATE TABLE CASTI_OBCE (
    KOD NUMBER(19),
    NAZEV VARCHAR2(50) NOT NULL,
    OBEC_KOD NUMBER(19) NOT NULL,
    CONSTRAINT PK_CASTI_OBCE PRIMARY KEY (KOD)
);

COMMENT ON TABLE CASTI_OBCE IS 'casti obce';

COMMENT ON COLUMN CASTI_OBCE.KOD IS 'Primární klíč.';

COMMENT ON COLUMN CASTI_OBCE.NAZEV IS 'názvy castí obcí';

COMMENT ON COLUMN CASTI_OBCE.OBEC_KOD IS 'Vazba na OBEC.KOD';

ALTER TABLE CASTI_OBCE ADD CONSTRAINT FK_CASTI_OBCE_OBEC FOREIGN KEY (OBEC_KOD) REFERENCES OBEC (KOD) ON DELETE CASCADE;
